*******************************

[rewrite_local]

^https?:\/\/([a-z0-9]+\.)?qsh\d+\.(?:com|cn|org\.cn)\/(?:source\/plugin\/qsts_app\/index\.php|mserver)(?:\/|$) url script-response-body 

[mitm] 

hostname = *.qsh*.com, *.qsh*.cn, *.qsh*.org.cn


*******************************/